// Name of the folder on Vsphere server.
folder = "ocp"

// Name of the vSphere server. The dev cluster is on "vcsa.vmware.devcluster.openshift.com".
vsphere_server = "svvcsa1p.orphenix.org"

// User on the vSphere server.
vsphere_user = "administrator@vsphere.local"

// Password of the user on the vSphere server.
vsphere_password = "@Cccpb09#"

// Name of the vSphere cluster. The dev cluster is "devel".
vsphere_cluster = "APPS"

// Name of the vSphere data center. The dev cluster is "dc1".
vsphere_datacenter = "OrphenixDC"

// Name of the vSphere data store to use for the VMs. The dev cluster uses "nvme-ds1".
vsphere_datastore = "APPS-1"

// Name of the VM template to clone to create VMs for the cluster. The dev cluster has a template named "rhcos-latest".
vm_template = "fcos_template"

// his is the name of the publicly accessible network for cluster ingress and access.
vm_network = "LAN"

// The number of control plane VMs to create. Default is 3.
control_plane_count = 3

// The number of compute VMs to create. Default is 3.
compute_count = 3

// Ignition config for the bootstrap machine. You should change the source, based on your environment.
bootstrap_ignition = <<END_OF_BOOTSTRAP_IGNITION
{"ignition":{"config":{"merge":[{"source":"http://sfnas1p.orphenix.org/okd45/bootstrap.ign","verification":{}}],"replace":{"source":null,"verification":{}}},"security":{"tls":{}},"timeouts":{},"version":"3.0.0"},"passwd":{},"storage":{},"systemd":{}}
END_OF_BOOTSTRAP_IGNITION

// Ignition config for the control plane machines. You should copy the contents of the master.ign generated by the installer.
control_plane_ignition = <<END_OF_MASTER_IGNITION
{"ignition":{"config":{"merge":[{"source":"https://api-int.okd.orphenix.org:22623/config/master"}]},"security":{"tls":{"certificateAuthorities":[{"source":"data:text/plain;charset=utf-8;base64,LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFRENDQWZpZ0F3SUJBZ0lJRGlYaU5wRk9Ud3d3RFFZSktvWklodmNOQVFFTEJRQXdKakVTTUJBR0ExVUUKQ3hNSmIzQmxibk5vYVdaME1SQXdEZ1lEVlFRREV3ZHliMjkwTFdOaE1CNFhEVEl3TVRJeE5ERTVNREF3T1ZvWApEVE13TVRJeE1qRTVNREF3T1Zvd0pqRVNNQkFHQTFVRUN4TUpiM0JsYm5Ob2FXWjBNUkF3RGdZRFZRUURFd2R5CmIyOTBMV05oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEzclliTTlCTmsxU04Kc29NM0Y3elN5UjJTeWxtSWxJek9MVVNhbXI3eGRrMmpPZ0hGdXhXU2hxUGRiUlRCNmhubVVUL1hVdEVZd2RiTgplNGhaU1NjRTBsVkltazRpM3Bmb21tdW5PeDdyUTdWditlcTVBdyt1Zkh1NjMwanA5U0FiR1hBYjdmVUpudnZCClRCSzkydFAyVm9qdXFrUUVlS3NXRjZuYmw3ZUcxczdibjl4YVY5dEMrdk04WUszMlg2VitnazZyc2NiY202ckMKYjd5T0NWcE8xSUlGQWgva2Njb3JDRlJRVWRTOTFXaW8wMlBTWnNUeUp1TDBoL2NjdHVZVjJvbktoaEhjYk0vNgprem1RZm83NEF5V0JVK2NpcXEwMHllT21icWwyUHFXdldNTGxhWUZSYW5rWFMybkZlTGU0Y0lCTlVnWGFOMXZQCkFYeE5hUWorTHdJREFRQUJvMEl3UURBT0JnTlZIUThCQWY4RUJBTUNBcVF3RHdZRFZSMFRBUUgvQkFVd0F3RUIKL3pBZEJnTlZIUTRFRmdRVWlDQytJbSsxT0ZFU3NiRDJmQWt2OTZnTUV6RXdEUVlKS29aSWh2Y05BUUVMQlFBRApnZ0VCQUN4TFRJOHNHUlpadDRQbW82ZjFJcjlWSHdQcVRnRFZ2L1Z6UlZwcVRIL0RMNEhuazV0d29Cb3hZb3FqCjZac0FpaW1iZURYMHE1Z2hGZnVSN1Bsc2ZCZkRkY2VLVnovT1FvYWtuU2MzMmNaVElybE9oSnBpVm9xcWowZXcKeGZ5eTNWVFdaUEllYnlUUklUSG9oODlYbHV0czBqd2lLejk2eXAvbnBlaCtELzlNMEkxQjNEZjYwWmdEblZncwpQNm9IalE3bWJNL0xWdDArR0tTV1ducmZMalQ0SXhwdElvOFFvTDhTM3R0QXA5cGdXSTh1MUtjNGtxZDc5M0FoCnF2QnZZZ0VRcHNqUWV2NVJBejN3aXhVd0tWMksvV05pOXpiV3AwL0tRYWZYZi9uZjlBVlU3MFZQQnF5KzQ3NGoKaEFPS0szZkFibk54ZThjNHBzQWEzUTlYY09nPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="}]}},"version":"3.1.0"}}
END_OF_MASTER_IGNITION

// Ignition config for the compute machines. You should copy the contents of the worker.ign generated by the installer.
compute_ignition = <<END_OF_WORKER_IGNITION
{"ignition":{"config":{"merge":[{"source":"https://api-int.okd.orphenix.org:22623/config/worker"}]},"security":{"tls":{"certificateAuthorities":[{"source":"data:text/plain;charset=utf-8;base64,LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFRENDQWZpZ0F3SUJBZ0lJRGlYaU5wRk9Ud3d3RFFZSktvWklodmNOQVFFTEJRQXdKakVTTUJBR0ExVUUKQ3hNSmIzQmxibk5vYVdaME1SQXdEZ1lEVlFRREV3ZHliMjkwTFdOaE1CNFhEVEl3TVRJeE5ERTVNREF3T1ZvWApEVE13TVRJeE1qRTVNREF3T1Zvd0pqRVNNQkFHQTFVRUN4TUpiM0JsYm5Ob2FXWjBNUkF3RGdZRFZRUURFd2R5CmIyOTBMV05oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEzclliTTlCTmsxU04Kc29NM0Y3elN5UjJTeWxtSWxJek9MVVNhbXI3eGRrMmpPZ0hGdXhXU2hxUGRiUlRCNmhubVVUL1hVdEVZd2RiTgplNGhaU1NjRTBsVkltazRpM3Bmb21tdW5PeDdyUTdWditlcTVBdyt1Zkh1NjMwanA5U0FiR1hBYjdmVUpudnZCClRCSzkydFAyVm9qdXFrUUVlS3NXRjZuYmw3ZUcxczdibjl4YVY5dEMrdk04WUszMlg2VitnazZyc2NiY202ckMKYjd5T0NWcE8xSUlGQWgva2Njb3JDRlJRVWRTOTFXaW8wMlBTWnNUeUp1TDBoL2NjdHVZVjJvbktoaEhjYk0vNgprem1RZm83NEF5V0JVK2NpcXEwMHllT21icWwyUHFXdldNTGxhWUZSYW5rWFMybkZlTGU0Y0lCTlVnWGFOMXZQCkFYeE5hUWorTHdJREFRQUJvMEl3UURBT0JnTlZIUThCQWY4RUJBTUNBcVF3RHdZRFZSMFRBUUgvQkFVd0F3RUIKL3pBZEJnTlZIUTRFRmdRVWlDQytJbSsxT0ZFU3NiRDJmQWt2OTZnTUV6RXdEUVlKS29aSWh2Y05BUUVMQlFBRApnZ0VCQUN4TFRJOHNHUlpadDRQbW82ZjFJcjlWSHdQcVRnRFZ2L1Z6UlZwcVRIL0RMNEhuazV0d29Cb3hZb3FqCjZac0FpaW1iZURYMHE1Z2hGZnVSN1Bsc2ZCZkRkY2VLVnovT1FvYWtuU2MzMmNaVElybE9oSnBpVm9xcWowZXcKeGZ5eTNWVFdaUEllYnlUUklUSG9oODlYbHV0czBqd2lLejk2eXAvbnBlaCtELzlNMEkxQjNEZjYwWmdEblZncwpQNm9IalE3bWJNL0xWdDArR0tTV1ducmZMalQ0SXhwdElvOFFvTDhTM3R0QXA5cGdXSTh1MUtjNGtxZDc5M0FoCnF2QnZZZ0VRcHNqUWV2NVJBejN3aXhVd0tWMksvV05pOXpiV3AwL0tRYWZYZi9uZjlBVlU3MFZQQnF5KzQ3NGoKaEFPS0szZkFibk54ZThjNHBzQWEzUTlYY09nPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="}]}},"version":"3.1.0"}}
END_OF_WORKER_IGNITION

// The MAC address to assign to the bootstrap VM.
bootstrap_mac = "00:50:56:a8:a2:88"

// The MAC address to assign to the control_plane VMs.
control_plane_macs = ["00:50:56:a8:92:a5", "00:50:56:a8:ac:ee", "00:50:56:a8:6c:ea"]

// The MAC address to assign to the compute VMs.
compute_macs = ["00:50:56:a8:0a:ca", "00:50:56:a8:4e:8c", "00:50:56:a8:0d:00"]